{% set name = "tomli-w" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tomli_w-{{ version }}.tar.gz
  sha256: 2dd14fac5a47c27be9cd4c976af5a12d87fb1f0b4512f81d69cce3b35ae25021

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2.0,<4
  run:
    - python >=3.9

test:
  imports:
    - tomli_w
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tomli_w/
  summary: A lil' TOML writer
  description: Tomli-W is a Python library for writing TOML. It is a write-only counterpart to Tomli, which is a read-only TOML parser. Tomli-W is fully compatible with TOML v1.0.0.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/hukkin/tomli-w
  doc_url: https://github.com/hukkin/tomli-w/blob/master/README.md

extra:
  recipe-maintainers:
    - ocefpaf
